apiVersion: v1
kind: Service
metadata:
  name: composer
  labels:
    app: composer
spec:
  type: ClusterIP
  selector:
    app: composer
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
