apiVersion: v1
kind: Service
metadata:
  name: llm-server
  labels:
    app: llm-server
spec:
  type: ClusterIP
  selector:
    app: llm-server
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
