name: deploy

on:
  workflow_run:
    workflows: [composer]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via Ansible
        run: |
          cd infra/ansible
          ansible-playbook playbooks/deploy-services.yaml -i inventory/hosts.yaml
